# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip5', models.CharField(max_length=5)),
                ('zip4', models.CharField(blank=True, max_length=4, null=True)),
                ('long', models.CharField(blank=True, max_length=25, null=True)),
                ('lat', models.CharField(blank=True, max_length=25, null=True)),
                ('ubi', models.CharField(max_length=9)),
                ('license_number', models.CharField(max_length=25)),
                ('locationtype', models.CharField(max_length=1)),
                ('producer', models.BooleanField()),
                ('processor', models.BooleanField()),
                ('retail', models.BooleanField()),
                ('transactionid', models.IntegerField()),
                ('transactionid_original', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together=set([('license_number', 'ubi')]),
        ),
    ]
