# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField(editable=False)),
                ('sessiontime', models.DateTimeField()),
                ('transactionid', models.CharField(max_length=50)),
                ('transactionid_original', models.CharField(max_length=50)),
                ('deleted', models.BooleanField()),
                ('manifestid', models.CharField(max_length=16)),
                ('stopcount', models.PositiveSmallIntegerField()),
                ('from_location', models.CharField(max_length=50)),
                ('total_item_count', models.PositiveSmallIntegerField()),
                ('transporter_dob', models.CharField(max_length=50)),
                ('transporter_id', models.CharField(max_length=50)),
                ('transporter_name', models.CharField(max_length=50)),
                ('transporter_vehicle_details', models.CharField(max_length=50)),
                ('transporter_vehicle_identification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField(editable=False)),
                ('sessiontime', models.DateTimeField()),
                ('transactionid', models.CharField(max_length=50)),
                ('transactionid_original', models.CharField(max_length=50)),
                ('deleted', models.BooleanField()),
                ('manifestid', models.CharField(max_length=16)),
                ('stopnumber', models.PositiveSmallIntegerField()),
                ('inventoryid', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField(editable=False)),
                ('sessiontime', models.DateTimeField()),
                ('transactionid', models.CharField(max_length=50)),
                ('transactionid_original', models.CharField(max_length=50)),
                ('deleted', models.BooleanField()),
                ('manifestid', models.CharField(max_length=16)),
                ('stopnumber', models.PositiveSmallIntegerField()),
                ('arrive_time', models.DateTimeField()),
                ('depart_time', models.DateTimeField()),
                ('item_count', models.PositiveSmallIntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField(editable=False)),
                ('sessiontime', models.DateTimeField()),
                ('transactionid', models.IntegerField()),
                ('transactionid_original', models.IntegerField()),
                ('deleted', models.BooleanField()),
                ('inventoryid', models.CharField(max_length=16)),
                ('inventorytype', models.CharField(max_length=2)),
                ('strain', models.CharField(max_length=50)),
                ('lineprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manifestid', models.CharField(max_length=16)),
                ('manifest_stop', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('outbound_license', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='manifeststop',
            unique_together=set([('manifestid', 'stopnumber')]),
        ),
    ]
