# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='transactionid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transactionid_original',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='transactionid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manifestitem',
            name='transactionid_original',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manifeststop',
            name='transactionid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manifeststop',
            name='transactionid_original',
            field=models.IntegerField(),
        ),
    ]
